server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # vue-router in modalità history: qualunque rotta non-file ricade su index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
